services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auction_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    image: fahadbashir644/bidding:backend
    ports:
      - "8088:8088"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: fahadbashir644/bidding:frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
