name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bidding:backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/bidding:backend

    - name: Build & Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bidding:frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/bidding:frontend

    - name: Save SSH key
      run: |
        echo "${{ secrets.DROPLET_KEY }}" > droplet.pem
        chmod 600 droplet.pem

    - name: Upload docker-compose.yml to Droplet
      run: |
        scp -o StrictHostKeyChecking=no -i droplet.pem docker-compose.yml root@159.65.148.214:/root/bidding-app/docker-compose.yml

    - name: Upload backend .env file to Droplet
      run: |
        echo "${{ secrets.BACKEND_ENV_FILE }}" > backend.env
        ssh -o StrictHostKeyChecking=no -i droplet.pem root@159.65.148.214 "mkdir -p /root/bidding-app/backend"
        scp -o StrictHostKeyChecking=no -i droplet.pem backend.env root@159.65.148.214:/root/bidding-app/backend/.env

    - name: Deploy to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no -i droplet.pem root@159.65.148.214 << 'EOF'
          cd /root/bidding-app
          docker rm -vf $(docker ps -aq) || true
          docker rmi -f $(docker images -aq) || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/bidding:backend
          docker pull ${{ secrets.DOCKER_USERNAME }}/bidding:frontend
          docker compose down || true
          docker compose up -d
        EOF
