name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bidding:backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/bidding:backend

    - name: Build & Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bidding:frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/bidding:frontend

    - name: Save SSH key
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > fahad.bashir.pem
        chmod 600 fahad.bashir.pem

    - name: Upload docker-compose.yml to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i fahad.bashir.pem docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/bidding-app/docker-compose.yml

    - name: Upload backend .env file to EC2
      run: |
        echo "${{ secrets.BACKEND_ENV_FILE }}" > backend.env
        ssh -o StrictHostKeyChecking=no -i fahad.bashir.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p ~/bidding-app/backend"
        scp -o StrictHostKeyChecking=no -i fahad.bashir.pem backend.env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/bidding-app/backend/.env

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i fahad.bashir.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          sudo su
          cd ~/bidding-app
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bidding:backend
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bidding:frontend
          sudo docker compose down
          sudo docker compose up -d
        EOF
